### ISSUE TITLE
Increase  buffer size for fluent bit - lines are too long, skipping file

### ISSUE THREAD

**Issue by msmith99** [SumoLogic/tailing-sidecar#226]
Error message -

[input:tail:tail.0] file=/server.log requires a larger buffer size, lines are too long. Skipping file."

Root cause, is that the buffer size configured for fluent bit is too small, either this needs to be increased, or made configurable -

[INPUT]
    Name        tail
    Path        /home/logs/server/*.log
    Db          /tmp/ng.db
    Db.sync     Full
    Tag         nginx-log
    Buffer_Chunk_Size 320KB
    Buffer_Max_Size   520KB

**Comment by drozinpax8** [comment]
I'm getting the same error with application running on tomcat:

file=/usr/share/tomcat8/logs/app.log requires a larger buffer size, lines are too long. Skipping file.

Do we have a timeline to add this configuration?

**Comment by fgrelaud** [comment]
Hi,

do we have any news about this issue ?
we have same problem with nextcloud log.

file=/var/log/nextcloud/nextcloud.log requires a larger buffer size, lines are too long. Skipping file.

Regards,

**Comment by kkujawa-sumo** [comment]
I'm closing this issue,  if you still observe the issue, please reopen it ;)
