### ISSUE TITLE
Expose fluent-bit configurations

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/tailing-sidecar#30]
There may be needs to fine tune the fluent-bit configuration and it should be possible to do so (eg multiline processing)

**Comment by sumo-drosiek** [comment]
@SumoLogic/open-source-collection-team What do you think is better solution for this issue?

1. Expose only `inputs` configuration (handling specific file from configMap)
2. expose full configuration (mounting configMap as directory)

As this is advanced feature I would go with the second option

**Comment by kkujawa-sumo** [comment]
at this moment it is possible to overwrite sidecar configuration, see: https://github.com/SumoLogic/tailing-sidecar/blob/441c87117408eecd2c8a4ca6d8b72c074cc6058a/helm/tailing-sidecar-operator/values.yaml#L52C1-L62C16
