### ISSUE TITLE
Sidecar Container not starting

### ISSUE THREAD

**Issue by shaunfink** [SumoLogic/tailing-sidecar#335]
HI all

We're using version `2.7.0` of the official sumologic helm chart for deploying sumo to our EKS clusters. We've found a situation where we've had to make use of the tailing sidecar to ingest logs from a container for a service, as these logs are not written to stdout/stderr.

As the sumo chart has this bundled in as a dependant chart, it seems like the sidecar image is not working as expected, but is also running a MUCH older version of the chart (version `0.3.2`, based on what I can see in [Chart.yaml](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/Chart.yaml))

I get the following in logs when running the sidecar

```log
[2022/07/01 09:42:11] [error] [sqldb] cannot open database /tailing-sidecar/var/fluent-bit-state.db
[2022/07/01 09:42:11] [error] [input:tail:tail.0] could not open/create database
[2022/07/01 09:42:11] [error] Failed initialize input tail.0
[2022/07/01 09:42:11] [error] [lib] backend failed
```
Overriding the version of both the sidecar to version `0.5.0` seems to work a treat though.

Configs I'm defining in values.yaml for the sumo chart are the following:

```yaml
tailing-sidecar-operator:
  enabled: true
  
  sidecar:
    image:
      tag: 0.5.0
```

If I do overrides for later versions of the operator (pretty much anything up from 0.3.2), I see loads of these issues in operator logs (which look to relate to [#168](https://github.com/SumoLogic/tailing-sidecar/issues/168):

```log
E0701 10:10:45.493493       1 leaderelection.go:325] error retrieving resource lock monitoring/7b555970.sumologic.com: leases.coordination.k8s.io "7b555970.sumologic.com" is forbidden: User "system:serviceaccount:monitoring:tailing-sidecar-service-account" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "monitoring"
```

Reverting all these configs to use the 0.3.2 operator, and the 0.5.0 sidecar looks to work.

**Comment by sumo-drosiek** [comment]
This would be fixed by #377
