### ISSUE TITLE
Add cert-manger as helm chart dependency

### ISSUE THREAD

**Issue by kkujawa-sumo** [SumoLogic/tailing-sidecar#52]
[cert-manger](https://cert-manager.io/) could be added as helm chart dependency in Chart.yaml.
It will be good to detect if cert-manager was earlier installed in the cluster.

**Comment by perk-sumo** [comment]
We should try to remove the `cert manager` if we can (like the Telegraf Operator helm chart does).

**Comment by astencel-sumo** [comment]
Created follow-up issue to remove `cert-manager`: https://github.com/SumoLogic/tailing-sidecar/issues/84
