### ISSUE TITLE
Replace hostPath volume added to tailing sidecars with empytDir

### ISSUE THREAD

**Issue by kkujawa-sumo** [SumoLogic/tailing-sidecar#54]
Fluent Bit database is now saved in hostPath volume. It should be good save this database in emptyDir volume and then when Pod is deleted from node remaining files are also deleted.

**Comment by dlaidlaw** [comment]
Using an emptyDir volume would also mean the sidecar could run on AWS EKS Fargate instances. Fargate instances only support ephemeral volumes.

**Comment by kkujawa-sumo** [comment]
Closed by #160
