### ISSUE TITLE
Replace `cert-manager` with another method to generate certificates

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/tailing-sidecar#84]
To decrease the number of prerequisites to installing the operator, remove `cert-manager` with a different way to generate certificates.

Consider the solution used in Telegraf operator:
- https://github.com/influxdata/helm-charts/blob/046d1691553807922ee01fd525f3b1c4efdf0e96/charts/telegraf-operator/templates/tls.yml
- https://github.com/influxdata/helm-charts/blob/046d1691553807922ee01fd525f3b1c4efdf0e96/charts/telegraf-operator/templates/_helpers.tpl#L65-L113

**Comment by kkujawa-sumo** [comment]
closed by #88
